// app/layout.tsx
import { Geist_Mono, Inter } from "next/font/google";
import "./css/globals.css";
import { Header } from "@/components/ui/header";
import { ThemeProvider } from "@/components/theme-provider"
const inter = Inter({
  subsets: ["latin"],
  variables: "--font-inter",
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`
          ${inter.variable} 
          ${geistMono.variable} 
          bg-white text-gray-900 
          dark:bg-gray-950 dark:text-gray-200 
          antialiased
        `}
      >
         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >

    
            <Header />
            <main>{children}</main>
      
       </ThemeProvider>
      </body>
    </html>
  );
}
